ppedv.Finex/ppedv.Finex.UI.Web/Models/ErrorViewModel.cs
using System;

namespace ppedv.Finex.UI.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ppedv.Finex/ppedv.Finex.UI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ppedv.Finex.UI.Web.Models;

namespace ppedv.Finex.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ppedv.Finex/ppedv.Finex.UI.Web/Controllers/MediApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ppedv.Finex.Logic;
using ppedv.Finex.Model;

namespace ppedv.Finex.UI.Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class MediApiController : ControllerBase
    {
        Core core = new Core();
        // GET: api/MediApi
        [HttpGet]
        public IEnumerable<Medikament> Get()
        {
            return core.Repository.Query<Medikament>().ToList();
        }

        // GET: api/MediApi/5
        [HttpGet("{id}", Name = "Get")]
        public Medikament Get(int id)
        {
            return core.Repository.GetById<Medikament>(id);
        }

        // POST: api/MediApi
        [HttpPost]
        public void Post([FromBody] Medikament value)
        {
             core.Repository.Add<Medikament>(value);
            core.Repository.SaveChanges();
        }

        // PUT: api/MediApi/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] Medikament value)
        {
            core.Repository.Update<Medikament>(value);
            core.Repository.SaveChanges();

        }

        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

ppedv.Finex/ppedv.Finex.UI.Web/Controllers/MediController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ppedv.Finex.Logic;
using ppedv.Finex.Model;

namespace ppedv.Finex.UI.Web.Controllers
{
    public class MediController : Controller
    {
        Core core = new Core();

        // GET: Medi
        public ActionResult Index()
        {
            return View(core.Repository.Query<Medikament>().ToList());
        }

        // GET: Medi/Details/5
        public ActionResult Details(int id)
        {
            return View(core.Repository.GetById<Medikament>(id));
        }

        // GET: Medi/Create
        public ActionResult Create()
        {
            return View(new Medikament() { Name = "NEU", Packungsgröße = 17 });
        }

        // POST: Medi/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Medikament medi)
        {
            try
            {
                core.Repository.Add(medi);
                core.Repository.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Medi/Edit/5
        public ActionResult Edit(int id)
        {
            return View(core.Repository.GetById<Medikament>(id));
        }

        // POST: Medi/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Medikament medi)
        {
            try
            {
                core.Repository.Update(medi);
                core.Repository.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Medi/Delete/5
        public ActionResult Delete(int id)
        {
            return View(core.Repository.GetById<Medikament>(id));
        }

        // POST: Medi/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Medikament medi)
        {
            try
            {
                var loaded = core.Repository.GetById<Medikament>(id);
                if (loaded != null)
                {
                    core.Repository.Delete(loaded);
                    core.Repository.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ppedv.Finex/ppedv.Finex.UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ppedv.Finex/ppedv.Finex.UI.Web/Views/Medi/Create.cshtml
@model ppedv.Finex.Model.Medikament

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Medikament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nummer" class="control-label"></label>
                <input asp-for="Nummer" class="form-control" />
                <span asp-validation-for="Nummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Packungsgröße" class="control-label"></label>
                <input asp-for="Packungsgröße" class="form-control" />
                <span asp-validation-for="Packungsgröße" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preis" class="control-label"></label>
                <input asp-for="Preis" class="form-control" />
                <span asp-validation-for="Preis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modified" class="control-label"></label>
                <input asp-for="Modified" class="form-control" />
                <span asp-validation-for="Modified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ppedv.Finex/ppedv.Finex.UI.Web/Views/Medi/Delete.cshtml
@model ppedv.Finex.Model.Medikament

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medikament</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Packungsgröße)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Packungsgröße)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ppedv.Finex/ppedv.Finex.UI.Web/Views/Medi/Details.cshtml
@model ppedv.Finex.Model.Medikament

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Medikament</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nummer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nummer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Packungsgröße)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Packungsgröße)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ppedv.Finex/ppedv.Finex.UI.Web/Views/Medi/Edit.cshtml
@model ppedv.Finex.Model.Medikament

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Medikament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nummer" class="control-label"></label>
                <input asp-for="Nummer" class="form-control" />
                <span asp-validation-for="Nummer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Packungsgröße" class="control-label"></label>
                <input asp-for="Packungsgröße" class="form-control" />
                <span asp-validation-for="Packungsgröße" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preis" class="control-label"></label>
                <input asp-for="Preis" class="form-control" />
                <span asp-validation-for="Preis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modified" class="control-label"></label>
                <input asp-for="Modified" class="form-control" />
                <span asp-validation-for="Modified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ppedv.Finex/ppedv.Finex.UI.Web/Views/Medi/Index.cshtml
@model IEnumerable<ppedv.Finex.Model.Medikament>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nummer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Packungsgröße)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
 
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nummer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Packungsgröße)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
      
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ppedv.Finex/ppedv.Finex.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ppedv.Finex.UI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ppedv.Finex.UI.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medi" asp-action="Index">Medikamente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ppedv.Finex.UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>